export const LOAD_USERS_START = "LOAD_USERS_START";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_USERS_ERROR = "LOAD_USERS_ERROR";

export const CREATE_USER_START = "CREATE_USER_START";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_ERROR = "CREATE_USER_ERROR";

export const DELETE_USER_START = "DELETE_USER_START";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";

export const UPDATE_USER_START = "UPDATE_USER_START";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const LOAD_SINGLE_USER_START = "LOAD_SINGLE_USER_START";
export const LOAD_SINGLE_USER_SUCCESS = "LOAD_SINGLE_USER_SUCCESS";
export const LOAD_SINGLE_USER_ERROR = "LOAD_SINGLE_USER_ERROR";

export const LOAD_SEARCH_START = "LOAD_SEARCH_START";
export const LOAD_SEARCH_SUCCESS = "LOAD_SEARCH_SUCCESS";
export const LOAD_SEARCH_ERROR = "LOAD_SEARCH_ERROR";

export const FILTER_USER_START = "FILTER_USER_START";
export const FILTER_USER_SUCCESS = "FILTER_USER_SUCCESS";
export const FILTER_USER_ERROR = "FILTER_USER_ERROR";

export const SORT_USER_START = "SORT_USER_START";
export const SORT_USER_SUCCESS = "SORT_USER_SUCCESS";
export const SORT_USER_ERROR = "SORT_USER_ERROR";
